version: 2.1

orbs:
  ci: bigcommerce/internal@volatile

executors:
  go:
    working_directory: /go/src/github.com/bigcommerce/bonvoy
    docker:
      - image: circleci/golang:1.16

jobs:
  test:
    executor: go
    steps:
      - ci/pre-setup
      - run: make test
  build:
    executor: go
    steps:
      - ci/pre-setup
      - run: make deps build

workflows:
  version: 2
  full:
    jobs:
      - test
      - build
